### ISSUE TITLE
Create schema for API

### ISSUE THREAD

**Issue by MariusDieckmann** [ArunaStorage/ArunaAPI#25]
### Overview

Create the gRPC schema models and calls for the new API. Add proper documentation (in-code). 

### Tasks

- [x] First API version
- [x] Test for usability
- [x] Add CRUD operations for each resource

### Discussions

**Comment by St4NNi** [comment]
Fixed by #35
