### ISSUE TITLE
CI pipeline for API client generation

### ISSUE THREAD

**Issue by MariusDieckmann** [ArunaStorage/ArunaAPI#26]
### Overview

Set up the pipelines for individual programming languages to automatically create new client stubs for each release.

### Tasks

- [x] Test rust compile
- [x] Create automatic pipeline for rust
- [x] Test golang compile
- [x] Create automatic pipeline for golang
- [x] Test python compile
- [x] Create automatic pipeline for python

### Discussions

**Comment by St4NNi** [comment]
Fixed since 0.5.0
